/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_JNIdemo_JNIapp_CirclePainterWeb */

#ifndef _Included_com_JNIdemo_JNIapp_CirclePainterWeb
#define _Included_com_JNIdemo_JNIapp_CirclePainterWeb
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_JNIdemo_JNIapp_CirclePainterWeb
 * Method:    circleMove
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_JNIdemo_JNIapp_CirclePainterWeb_circleMove
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
