/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_JNIdemo_JNIapp_Test */

#ifndef _Included_com_JNIdemo_JNIapp_Test
#define _Included_com_JNIdemo_JNIapp_Test
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_JNIdemo_JNIapp_Test
 * Method:    testMehtod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_JNIdemo_JNIapp_Test_testMehtod
  (JNIEnv *, jobject);

/*
 * Class:     com_JNIdemo_JNIapp_Test
 * Method:    sumAndAverage
 * Signature: ([I)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_com_JNIdemo_JNIapp_Test_sumAndAverage
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
