/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_JNIdemo_JNIapp_RaceTrackPainterWeb */

#ifndef _Included_com_JNIdemo_JNIapp_RaceTrackPainterWeb
#define _Included_com_JNIdemo_JNIapp_RaceTrackPainterWeb
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_JNIdemo_JNIapp_RaceTrackPainterWeb
 * Method:    Figure8Move
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_JNIdemo_JNIapp_RaceTrackPainterWeb_Figure8Move
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
